server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: practice1
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create    
    properties:      
      show-sql: true
      format_sql: true
        
    
      
    
      